# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localnumber < Formula
  desc "Small command line application for formatting phone numbers in a local format."
  homepage "https://vin047.com/"
  version "0.0.1"
  license "AGPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vin047/localnumber/releases/download/v0.0.1/localnumber-v0.0.1-macos-amd64.tar.gz"
      sha256 "456e1dc564c66386693d17b24c29d4febe7b145319c46f8c8581bcfe59a57810"

      def install
        bin.install "localnumber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vin047/localnumber/releases/download/v0.0.1/localnumber-v0.0.1-macos-arm64.tar.gz"
      sha256 "2350d13c83b37c4d78daaff8463f51e5633874b96f7288c213c76303f6d34c2c"

      def install
        bin.install "localnumber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vin047/localnumber/releases/download/v0.0.1/localnumber-v0.0.1-linux-armv6.tar.gz"
      sha256 "76abe685ddf08c8721ca35d2b412f4e6a6040511d4a74964eb378d1783d072d0"

      def install
        bin.install "localnumber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vin047/localnumber/releases/download/v0.0.1/localnumber-v0.0.1-linux-amd64.tar.gz"
      sha256 "cefcd8ecbeff16d40c71869d21bb8809a6c3499336facfe22efdc1945b747bd8"

      def install
        bin.install "localnumber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vin047/localnumber/releases/download/v0.0.1/localnumber-v0.0.1-linux-arm64.tar.gz"
      sha256 "caabf3102086db9cd55b99e395e0e418c6173dbbd43003782e87aeeb078078d0"

      def install
        bin.install "localnumber"
      end
    end
  end
end
